### ISSUE TITLE
Minimongo?

### ISSUE THREAD

**Issue by edemaine** [harryadel/blastjs#4]
Just came across your handy project! Coincidentally, I made [this repo](https://github.com/edemaine/meteor-tracker) which ported just Tracker and ReactiveVar, so that I could test [some Meteor code](https://github.com/edemaine/solidjs-meteor-data) outside Meteor, but your Blast is quite a bit more extensive (and works just as well -- I tested).

Do you have plans to port over Minimongo? You have some of the dependencies, like DiffSequence, already ported. I'd definitely find this handy for my testing purposes again, but no pressure of course.

**Comment by harryadel** [comment]
Hello @edemaine glad you find my little experiment of use. I was actually afraid that some has already done this in any capacity but I guess I'm too far in to call it quits. :sweat_smile:    

>Do you have plans to port over Minimongo? You have some of the dependencies, like DiffSequence, already ported. I'd definitely find this handy for my testing purposes again, but no pressure of course.

I kind of do. This experiment was to test how portable Meteor is to NPM/vanilla JS and since Blaze is one of the most Meteor-y parts of Meteor this definitely showed me how easy it'd be to port other parts of Meteor to NPM. So once I wrap up this project [btw webpack example works now], I'm going to conduct another experiment with Meteor and see how far I can push it and I'll surely reach out to you when Minimongo gets done though you don't have to wait for me nor hold me against my word I tend to change my opinions pretty quickly. :sweat_smile:

**Comment by edemaine** [comment]
Awesome, thanks! Do keep me posted, and likewise, if I timeout and try porting (Mini)Mongo myself, I'll let you know. 🙂

**Comment by harryadel** [comment]
I sure will. Let the race begin! :smile:

**Comment by harryadel** [comment]
Hey @edemaine, [minimongo](https://www.npmjs.com/package/@blastjs/minimongo) is now ready. I tried to reach you via the forums but it seems you don't check them out as frequent.
